// <auto-generated />
using GuiHuaWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuiHuaWebApp.Migrations
{
    [DbContext(typeof(GuiHuaWebAppContext))]
    partial class GuiHuaWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuiHuaWebApp.Models.GuiHuaJianDu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BeiZhu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GongGuiNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked1")
                        .HasColumnType("bit");

                    b.Property<bool>("IsChecked2")
                        .HasColumnType("bit");

                    b.Property<string>("JSDanWei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("JSGuiMo")
                        .HasColumnType("float");

                    b.Property<string>("JSWeiZhi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrjName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SFFaWenXinTiShiKa")
                        .HasColumnType("bit");

                    b.Property<bool>("SFJunGongHeShi")
                        .HasColumnType("bit");

                    b.Property<bool>("SFYanXian")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem1")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem2")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem3")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem4")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem5")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem6")
                        .HasColumnType("bit");

                    b.Property<bool>("checkItem7")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GuiHuaJianDu");
                });
#pragma warning restore 612, 618
        }
    }
}
